#!/bin/bash
for i in {1..9}
do
    path=/home/student/Desktop/workspace/marker_color_hard/
    marker=marker_color_hard_0
    marker+=$i
    marker+=.png
    path+=$marker
    pathout+=$marker
    echo $path
    ./cmake-build-debug/visionFinal $path -time=1 -hard=1
done

for i in {10..52}
do
    path=/home/student/Desktop/workspace/marker_color_hard/
    marker=marker_color_hard_
    marker+=$i
    marker+=.png
    path+=$marker
    pathout+=$marker
    echo $path
    ./cmake-build-debug/visionFinal $path -time=1 -hard=1
done
