#!/bin/bash
for i in {1..9}
do
    path=/home/student/Desktop/workspace/marker_corny/
    marker=marker_corny_0
    marker+=$i
    marker+=.png
    path+=$marker
    pathout+=$marker
    echo $path
    ./cmake-build-debug/marker3 Marker3.ppm $path -output=$marker
done

for i in {10..30}
do
    path=/home/student/Desktop/workspace/marker_corny/
    marker=marker_corny_
    marker+=$i
    marker+=.png
    path+=$marker
    pathout+=$marker
    echo $path
    ./cmake-build-debug/marker3 Marker3.ppm $path -output=$marker
done

